apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: us-central1-docker.pkg.dev/sirisha-test1/postgres-gke-demo/postgres-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_DB
            value: "pgdb"
          - name: POSTGRES_USER
            value: "pguser"
          - name: POSTGRES_PASSWORD
            value: "pgpassword"
